# Generated by Django 2.1.1 on 2018-10-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(choices=[('E-001', 'BLQ-01'), ('E-002', 'BLQ-02'), ('E-003', 'BLQ-03'), ('E-004', 'BLQ-04'), ('E-005', 'BLQ-05'), ('E-006', 'BLQ-06'), ('E-007', 'BLQ-07'), ('E-008', 'BLQ-08'), ('E-009', 'BLQ-09'), ('E-011', 'BLQ-11'), ('E-012', 'BLQ-12'), ('M-001', 'BLQ-01'), ('M-002', 'BLQ-02'), ('M-003', 'BLQ-03'), ('M-004', 'BLQ-04'), ('M-005', 'BLQ-05'), ('M-006', 'BLQ-06'), ('M-007', 'BLQ-07'), ('M-008', 'BLQ-08'), ('M-019', 'BLQ-09'), ('M-010', 'BLQ-10'), ('M-011', 'BLQ-11'), ('E-012', 'BLQ-12')], max_length=22)),
                ('ler_entrada', models.CharField(default=0, max_length=10)),
                ('ler_saida', models.CharField(default=0, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estacao_leitura', models.ManyToManyField(to='estacoes.Estacao')),
            ],
        ),
    ]
