# Generated by Django 2.1.1 on 2018-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='nome',
            field=models.TextField(choices=[('CHI', '1 - Chico da Silva'), ('JAL', '2 - José de Alencar'), ('SBE', '3 - São Benedito'), ('BEN', '4 - Benfica'), ('PCI', '5 - Padre Cícero'), ('POR', '6 - Porangabussu'), ('COU', '7 - Couto Fernandes'), ('JUK', '8 - Juscelino Kubsheck'), ('PAR', '9 - Parangaba'), ('VIP', '10 - Vila Pery'), ('SAT', '11 - Manoel Sátiro'), ('MON', '12 - Mondubim'), ('ESP', '13 - Esperança'), ('ARA', '14 - Aracapé'), ('ALT', '15 - Alto Alegre'), ('RAQ', '16 - Raquel de Queiróz'), ('VIT', '17 - Virgílio Távora'), ('MAR', '18 - Maracanaú'), ('JER', '19 - Jereissati'), ('CAB', '20 - Carlito Benevides')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leitura',
            name='tipo',
            field=models.TextField(choices=[('1', 'Eletrônico'), ('2', 'Mecânico')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leitura',
            name='gate',
            field=models.TextField(choices=[('BLQ-01', 'E-001'), ('BLQ-02', 'E-002'), ('BLQ-03', 'E-003'), ('BLQ-04', 'E-004'), ('BLQ-05', 'E-005'), ('BLQ-06', 'E-006'), ('BLQ-07', 'E-007'), ('BLQ-08', 'E-008'), ('BLQ-09', 'E-009'), ('BLQ-11', 'E-011'), ('BLQ-12', 'E-012'), ('BLQ-01', 'M-001'), ('BLQ-02', 'M-002'), ('BLQ-03', 'M-003'), ('BLQ-04', 'M-004'), ('BLQ-05', 'M-005'), ('BLQ-06', 'M-006'), ('BLQ-07', 'M-007'), ('BLQ-08', 'M-008'), ('BLQ-09', 'M-019'), ('BLQ-10', 'M-010'), ('BLQ-11', 'M-011'), ('BLQ-12', 'E-012')]),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='ler_entrada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='ler_saida',
            field=models.IntegerField(default=0),
        ),
    ]
