# Generated by Django 2.1.1 on 2018-10-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
        ('estacoes', '0002_auto_20181019_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='gates',
        ),
        migrations.AddField(
            model_name='estacao',
            name='gates',
            field=models.ManyToManyField(to='gates.Gate'),
        ),
    ]
